=== WaaRvEn/PRACTICA-FINAL-LENGUAJE-DE-MARCAS/HTML/Steven Nata Examen 2EV/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="veladas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="velada" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fecha" type="xs:date"/>
              <xs:element name="ubicacion" type="xs:string"/>
              <xs:element name="combates">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="combate" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="boxeador1" type="xs:string"/>
                          <xs:element name="boxeador2" type="xs:string"/>
                          <xs:element name="resultado" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== WaaRvEn/PRACTICA-FINAL-LENGUAJE-DE-MARCAS/HTML/Steven Nata Examen 2EV/EJERCICIO5.xml
<?xml version="1.0" encoding="UTF-8"?>
<veladas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
  <velada>
    <fecha>2024-02-14</fecha>
    <ubicacion>Madrid</ubicacion>
    <combates>
      <combate>
        <boxeador1>Pepe</boxeador1>
        <boxeador2>Juan</boxeador2>
        <resultado>Ganador Juan</resultado>
      </combate>
      <combate>
        <boxeador1>Manolo</boxeador1>
        <boxeador2>Gustabo</boxeador2>
        <resultado>Gustabo</resultado>
      </combate>
    </combates>
  </velada>
</veladas>
